name: Setup Production

on: [workflow_dispatch]

jobs:
    setup-production:
        name: Meteor setup
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Unlock secrets
              uses: sliteteam/github-action-git-crypt-unlock@1.2.0
              env:
                  GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

            - name: Script test
              run: chmod +x ./.github/script.sh && sh ./.github/script.sh