name: Meteor setup and deploy

on: [workflow_dispatch]

jobs:
    setup-production:
        name: Meteor setup
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Unlock secrets
              uses: sliteteam/github-action-git-crypt-unlock@1.2.0
              env:
                  GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
            
            - name: Install SSH key
              uses: shimataro/ssh-key-action@v2
              with:
                key: ${{ secrets.SSH_KEY }}
                name: id_rsa
                known_hosts: ${{ secrets.KNOWN_HOSTS }}
                if_key_exists: replace

            - name: Setup meteor env
              uses: meteorengineer/setup-meteor@v1
      
            - name: Install dependencies
              run: meteor npm install

            - name: Install mup, do setup, and deploy
              run: |
                npm install mup
                npm run mup-setup
                npm run mup-deploy